version: '3'

services:

  app:
    image: "14.15.1"
    container_name: nest-app
    build: 
      context: .
      dockerfile: Dockerfile.prod
    entrypoint:  ./.docker/entrypoint.sh
    
    
    ports:
      - 3333:3333
    
     
    

  

